### ISSUE TITLE
Comments in code

### ISSUE THREAD

**Issue by betonomochalka** [winstxnhdw/raft-hax#1]
Can you make comments in code for people who want learn codding by your code)))

**Comment by betonomochalka** [comment]
it can help someone

**Comment by winstxnhdw** [comment]
Hey @betonomochalka,

I would love to add a comment for every single line of my code, but unfortunately, doing so will take a lot of time that I do not have as of right now. 

I try to write self-explanatory code for programmers already familiar with the C# syntax, and if there are some parts of it which are still difficult to understand, feel free to ask about them here :)

**Comment by betonomochalka** [comment]
okey thx
